_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
JOB_ID:
    value: run1
batchsize:
    value: 1
dataset:
    value: ./Dataset/
learning_rate:
    value: 0.0001
